spring.application.name=SriMohanSalesServices

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/srimohan_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Time_Taker.00

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=SriMohanSalesSecretKey2026VeryLongKey
jwt.expiration=86400000